name: Deploy to WordPress
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to WordPress
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: betterthanexcel.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /wp-content/themes/generatepress-child/